---
title: "NFL Week 6 MA206"
author: "MAJ Daniel Baller"
date: "8/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(data.table)
library(formattable)
library(ggpubr)
library(ggrepel)
# week_1 = read_csv("NFL Week 1.csv")
# week_2 = read_csv("NFL Week 2.csv")
# week_3 = read_csv("NFL Week 3.csv")
# week_4 = read_csv("NFL Week 4.csv")
# week_5 = read_csv("NFL Week 5.csv")
# data = read_csv("NFL Week 6.csv") # Update
week_1 = read_csv("NFL Week 1 Prediction MA206.csv")
week_2 = read_csv("NFL Week 2 MA206.csv")
week_3 = read_csv("NFL Week 3 MA206.csv")
week_4 = read_csv("NFL Week 4 MA206.csv")
week_5 = read_csv("NFL Week 5 MA206.csv")
data = read_csv("NFL Week 6 MA206.csv") # Update
```

```{r games, include=FALSE}
#basic info

n = 13 #number of games this week
wk1_n = 16 # number of games in week 1
wk2_n = 16 # number of games in week 2
wk3_n = 16 # number of games in week 3
wk4_n = 15 # number of games in week 4
wk5_n = 15 # number of games in week 4
g1_n = 16 # number of group picks in week 1
g2_n = 16 # number of group picks in week 2
g3_n = 16 # number of group picks in week 3
g4_n = 15 # number of group picks in week 4
g5_n = 13 # number of group picks in week 4
wk1_wins = 10 #number of wins in week 1
wk2_wins = 10 #number of wins in week 2
wk3_wins = 12 #number of wins in week 3
wk4_wins = 8 #number of wins in week 4 
wk5_wins = 8 #number of wins in week 5 #update this
wk1_combined_wins = 12 # number of combined wins in week 1
wk2_combined_wins = 10 # number of combined wins in week 2
wk3_combined_wins = 10 # number of combined wins in week 3 
wk4_combined_wins = 8 # number of combined wins in week 4 
wk5_combined_wins = 9 # number of combined wins in week 5 # update this

# who actually won
winners = c("New England Patriots","Carolina Panthers","Washington Redskins","Minnesota Vikings","Houston Texans","New Orleans Saints","Seattle Seahawks","San Francisco 49ers","Arizona Cardinals","New York Jets","Denver Broncos","Pittsburgh Steelers","Green Bay Packers")

CBSsports = c("New England Patriots","Tampa Bay Buccaneers","Washington Redskins","Philadelphia Eagles","Kansas City Chiefs","New Orleans Saints","Seattle Seahawks","San Francisco 49ers","Atlanta Falcons","Dallas Cowboys","Tennessee Titans","Los Angeles Chargers","Green Bay Packers")

wk1_winners = c("Green Bay Packers","Minnesota Vikings","Baltimore Ravens","Buffalo Bills","Kansas City Chiefs","Los Angeles Rams","Tennessee Titans","Philadelphia Eagles","Seattle Seahawks","Los Angeles Chargers","TIE","Dallas Cowboys","San Francisco 49ers","New England Patriots","New Orleans Saints","Oakland Raiders")

wk2_winners = c("Tampa Bay Buccaneers","Baltimore Ravens","Dallas Cowboys","Indianapolis Colts","Seattle Seahawks","Buffalo Bills","San Fransisco 49ers","Detroit Lions","Green Bay Packers","Houston Texans","New England Patriots","Kansas City Chiefs","Los Angeles Rams","Chicago Bears","Atlanta Falcons","Cleveland Browns")

wk3_winners = c("Jacksonville Jaguars","Buffalo Bills","Detroit Lions","New England Patriots","Minnesota Vikings","Kansas City Chiefs","Indianapolis Colts","Green Bay Packers","Dallas Cowboys","New York Giants","Carolina Panthers","San Francisco 49ers","New Orleans Saints","Houston Texans","Los Angeles Rams","Chicago Bears") 

wk4_winners = c("Philadelphia Eagles","Tennessee Titans","New York Giants","Los Angeles Chargers","Oakland Raiders","Carolina Panthers","Kansas City Chiefs","Cleveland Browns","New England Patriots","Tampa Bay Buccaneers","Seattle Seahawks","Chicago Bears","Jacksonville Jaguars","New Orleans Saints","Pittsburgh Steelers")

wk5_winners = c("Seattle Seahawks","Carolina Panthers","New England Patriots","Buffalo Bills","Baltimore Ravens","Arizona Cardinals","Houston Texans","New Orleans Saints","Minnesota Vikings","Oakland Raiders","Philadelphia Eagles","Denver Broncos","Green Bay Packers","Indianapolis Colts","San Francisco 49ers") #update this

#wk1_CBSsports = c("Green Bay Packers","Atlanta Falcons","Miami Dolphins","New York Jets","Kansas City Chiefs","Carolina Panthers","Cleveland Browns","Philadelphia Eagles","Seattle Seahawks","Indianapolis Colts","Arizona Cardinals","Dallas Cowboys","Tampa Bay Buccaneers","Pittsburgh Steelers","New Orleans Saints","Oakland Raiders")

#wk2_CBSsports = c("Carolina Panthers","Baltimore Ravens","Dallas Cowboys","Indianapolis Colts","Seattle Seahawks","Buffalo Bills","Cincinnati Bengals","Los Angeles Chargers","Green Bay Packers","Houston Texans","New England Patriots","Kansas City Chiefs","Los Angeles Rams","Chicago Bears","Philadelphia Eagles","Cleveland Browns")

#wk3_CBSsports = c("Jacksonville Jaguars","Buffalo Bills","Philidelphia Eagles","New England Patriots","Minnesota Vikings","Baltimore Ravens","Atlanta Falcons","Green Bay Packers","Dallas Cowboys","Tampa Bay Buccaneers","Carolina Panthers","San Francisco 49ers","Seattle Seahawks","Los Angeles Chargers","Los Angeles Rams","Chicago Bears") 

#wk4_CBSsports = c("Green Bay Packers","Atlanta Falcons","Washington Redskins","Los Angeles Chargers","Indianapolis Colts","Carolina Panthers","Kansas City Chiefs","Baltimore Ravens","New England Patriots","Los Angeles Rams","Seattle Seahawks","Chicago Bears","Jacksonville Jaguars","Dallas Cowboys","Pittsburgh Steelers")

#Wk5_CBSsports = c("Seattle Seahawks","Jacksonville Jaguars","New England Patriots","Tennessee Titans","Baltimore Ravens","Cincinnati Bangals","Houston Texans","Tamps Bay Buccaneers","Minnesota Vikings","Chicago Bears","Philadelphia Eagles","Los Angeles Chargers","Dallas Cowboys","Kansas City Chiefs","Cleveland Browns")

experts = ifelse(winners == CBSsports, 1, 0)
CBS = round(sum(experts)/n,4)
```

## Group Predictions

```{r Group Predictions, include=FALSE}
games = data %>% janitor::clean_names() %>%
  select(starts_with("game"))  #Creating the set of just games


# creating a table of predictions and votes for and against the prediction
pred_table = data.frame(Game=colnames(games), 
                        t(sapply(games, # apply following function to each column
                                 function(x) {
                                   t_x <- sort(table(x), decreasing=TRUE) # get the frequencies and sort them in decreasing order
                                   list(Prediction=names(t_x)[1], # name of the value with highest frequency
                                        votes_for=t_x[1], # highest frequency
                                        votes_against=t_x[2]) # Lowest Freq
                                 })))

#establish vectors for precictions and votes for and against
pred_table = pred_table %>% 
  mutate(votes_against = ifelse(is.na(pred_table$votes_against)==T, 0, as.integer(pred_table$votes_against))) # turning NA in votes against column into 0
pred = ifelse(as.numeric(pred_table$votes_for) == as.numeric(pred_table$votes_against), "Tie", as.character(pred_table$Prediction)) #choosing prediction or tie if no prediction
#votes_for = ifelse(is.na(pred_table$votes_for)==T, 0, as.integer(pred_table$votes_for))
votes_for = as.integer(pred_table$votes_for)
votes_against = as.integer(pred_table$votes_against)

results = tibble(Game = 1:length(games)) %>% 
  add_column(Prediction = pred) %>%
  add_column(Winners = winners) %>%
  mutate(Correct = ifelse(Prediction =="Tie", "--", ifelse(Prediction == Winners, "Yes", "No"))) %>%
  mutate(Correct_Votes = ifelse(Prediction == winners, votes_for, ifelse(winners == "TIE", 0, votes_against))) %>%
  mutate(Percentage_For = round(Correct_Votes/dim(data)[1],4)) %>%
  rename("Correct Votes" = Correct_Votes) %>%
  rename("Correct Percent" = Percentage_For)
results
```

```{r displaying group results, echo=FALSE}
# formating for color of table
improvement_formatter2 <- 
  formatter("span", 
            style = x ~ style(
              font.weight = "bold", 
              color = ifelse(x == "Yes", "green", ifelse(x =="No", "red", "black"))))


# Creatign Group Prediction table            
formattable(results, 
            align =c("c","c","c"), 
            list(
              `Indicator Name` = formatter("span", 
                                style = ~ style(color = "grey",font.weight = "bold")),
                                "Correct" = improvement_formatter2))

# Printing the weekly and season win percentage            
correct_count = count(results, Correct)
weekly_win_percentage = round(correct_count$n[which(correct_count$Correct == "Yes")]/(n-ifelse(identical(correct_count$n[which(correct_count$Correct == "--")], integer(0))==TRUE, 0, correct_count$n[which(correct_count$Correct == "--")])),4)
paste("Our win percentage for the week is", weekly_win_percentage, sep = " ")
paste("CBS Sports win percentage for the week is", CBS, sep = " ")
group_games = (n-ifelse(identical(correct_count$n[which(correct_count$Correct == "--")], integer(0))==TRUE, 0, correct_count$n[which(correct_count$Correct == "--")]))
season_games = group_games+g1_n+g2_n+g3_n+g4_n+g5_n
season_wins  = wk1_wins+wk2_wins+wk3_wins+wk4_wins+correct_count$n[which(correct_count$Correct == "Yes")]
season_win_percentage = round(season_wins/(season_games),4)
paste("Our season win percentage so far is", season_win_percentage, sep = " ")
paste("Games picked this season", season_games, sep = " ")
paste("Correct Games this season", season_wins, sep = " ")
Total = dim(data)[1]
paste(Total, "predictions this week", sep = " ")
```

```{r plotting group results, echo=FALSE}
#Previous Weeks
wins = round(c((wk1_wins/g1_n),(wk2_wins/g2_n),(wk3_wins/g3_n), (wk4_wins/g4_n), (wk5_wins/g5_n), weekly_win_percentage),4)
weeks = c("Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6")
df = as.data.frame(wins, weeks)

ggplot(df, aes(x = weeks, y = wins, group = 1))+
  geom_point()+
  geom_line()+
  geom_text(aes(label=wins),hjust=0, vjust=-1.5)+
  ylim(c(0, 1)) +
  xlab("NFL Week") + 
  ylab("Correct Percentage")+
  ggtitle("Weekly Group Correct Percentage")+
  theme_classic()
```

## Individual Predictions

```{r wk1 individual, include=FALSE}
# Calculating Week 1 Individual Results
indiv_wk1 = week_1 %>%
  select(`Name`, `Game 1`,`Game 2`, `Game 3`, `Game 4`, `Game 5`, `Game 6`, `Game 7`, `Game 8`, `Game 9`, `Game 10`, `Game 11`, `Game 12`, `Game 13`, `Game 14`, `Game 15`, `Game 16`) %>%  janitor::clean_names()

# Week 1 Individual Results

games_wk1 = week_1 %>% janitor::clean_names() %>%
  select(starts_with("game"))  #Creating the set of just games

indiv_correct_wk1 = NULL
help_wk1 = NULL
for (i in 1:length(indiv_wk1$name)){
  for(j in 1:length(games_wk1)){
    help_wk1[j] = ifelse(games_wk1[i,j]==wk1_winners[j],1,0)
  indiv_correct_wk1[i] = sum(help_wk1)
  }
}

# Calculating individual win number for week 1
season_wk1 = indiv_wk1 %>%
  select(name) %>%
  add_column(Week_1 = indiv_correct_wk1)

season = season_wk1

# Calculating Week 2 Individual Results
indiv_wk2 = week_2 %>%
  select(`Name`, `Game 1`,`Game 2`, `Game 3`, `Game 4`, `Game 5`, `Game 6`, `Game 7`, `Game 8`, `Game 9`, `Game 10`, `Game 11`, `Game 12`, `Game 13`, `Game 14`, `Game 15`, `Game 16`) %>%  janitor::clean_names()

games_wk2 = week_2 %>% janitor::clean_names() %>%
  select(starts_with("game"))  #Creating the set of just games

indiv_correct_wk2 = NULL
help_wk2 = NULL
for (i in 1:length(indiv_wk2$name)){
  for(j in 1:length(games_wk2)){
    help_wk2[j] = ifelse(games_wk2[i,j]==wk2_winners[j],1,0)
  indiv_correct_wk2[i] = sum(help_wk2)
  }
}

# Calculating individual win number for week 2
season_wk2 = indiv_wk2 %>%
  select(name) %>%
  add_column(Week_2 = indiv_correct_wk2)

# Adding week 2 results to week 1 
season = season %>%
  full_join(season_wk2)

# Calculating Week 3 Individual Results
indiv_wk3 = week_3 %>%
  select(`Name`, `Game 1`,`Game 2`, `Game 3`, `Game 4`, `Game 5`, `Game 6`, `Game 7`, `Game 8`, `Game 9`, `Game 10`, `Game 11`, `Game 12`, `Game 13`, `Game 14`, `Game 15`, `Game 16`) %>%  janitor::clean_names()

games_wk3 = week_3 %>% janitor::clean_names() %>%
  select(starts_with("game"))  #Creating the set of just games

indiv_correct_wk3 = NULL
help_wk3 = NULL
for (i in 1:length(indiv_wk3$name)){
  for(j in 1:length(games_wk3)){
    help_wk3[j] = ifelse(games_wk3[i,j]==wk3_winners[j],1,0)
  indiv_correct_wk3[i] = sum(help_wk3)
  }
}

# Calculating individual win number for week 3
season_wk3 = indiv_wk3 %>%
  select(name) %>%
  add_column(Week_3 = indiv_correct_wk3)

# Adding week 3 to week 1 and 2 
season = season %>%
  full_join(season_wk3)

# Calculating Week 4 Individual Results
indiv_wk4 = week_4 %>%
  select(`Name`, `Game 1`,`Game 2`, `Game 3`, `Game 4`, `Game 5`, `Game 6`, `Game 7`, `Game 8`, `Game 9`, `Game 10`, `Game 11`, `Game 12`, `Game 13`, `Game 14`, `Game 15`) %>%  janitor::clean_names()

games_wk4 = week_4 %>% janitor::clean_names() %>%
  select(starts_with("game"))  #Creating the set of just games

indiv_correct_wk4 = NULL
help_wk4 = NULL
for (i in 1:length(indiv_wk4$name)){
  for(j in 1:length(games_wk4)){
    help_wk4[j] = ifelse(games_wk4[i,j]==wk4_winners[j],1,0)
  indiv_correct_wk4[i] = sum(help_wk4)
  }
}

# Calculating individual win number for week 4
season_wk4 = indiv_wk4 %>%
  select(name) %>%
  add_column(Week_4 = indiv_correct_wk4)

# Adding week 4 to week 1-3
season = season %>%
  full_join(season_wk4)

# Calculating Week 5 Individual Results
indiv_wk5 = week_5 %>%
  select(`Name`, `Game 1`,`Game 2`, `Game 3`, `Game 4`, `Game 5`, `Game 6`, `Game 7`, `Game 8`, `Game 9`, `Game 10`, `Game 11`, `Game 12`, `Game 13`, `Game 14`, `Game 15`) %>%  janitor::clean_names()

games_wk5 = week_5 %>% janitor::clean_names() %>%
  select(starts_with("game"))  #Creating the set of just games

indiv_correct_wk5 = NULL
help_wk5 = NULL
for (i in 1:length(indiv_wk5$name)){
  for(j in 1:length(games_wk5)){
    help_wk5[j] = ifelse(games_wk5[i,j]==wk5_winners[j],1,0)
  indiv_correct_wk5[i] = sum(help_wk5)
  }
}

# Calculating individual win number for week 4
season_wk5 = indiv_wk5 %>%
  select(name) %>%
  add_column(Week_5 = indiv_correct_wk5)

# Adding week 5 to week 1-4
season = season %>%
  full_join(season_wk5)
```

```{r individual, include=FALSE}
# Creating the set of names and games

indiv = data %>%
  select(`Name`,`Hour`, `Game 1`,`Game 2`, `Game 3`, `Game 4`, `Game 5`, `Game 6`, `Game 7`, `Game 8`, `Game 9`, `Game 10`, `Game 11`, `Game 12`, `Game 13`) %>%  janitor::clean_names()

# Counting the correct number of pics for each person  

indiv_correct = NULL
help = NULL
for (i in 1:length(indiv$name)){
  for(j in 1:length(games)){
    help[j] = ifelse(games[i,j]==winners[j],1,0)
  indiv_correct[i] = sum(help)
  }
}

# Calculating individual win percentage, combining data and orderign by percentage 
indiv = indiv %>% 
  add_column(WK6_Correct = indiv_correct) %>%
  mutate(WK6_Percent = round(WK6_Correct/n,4)) %>%
  rename("Week_6" = WK6_Correct)%>%
  rename("Percent" = WK6_Percent)%>%
  arrange(-Percent)

# choosing just name # correct pics and correct percentage
indiv_disp = indiv %>%
  select(name,hour, Week_6, Percent) %>%
  full_join(season) %>%
  mutate(w1p = ifelse(is.na(Week_1)==T,0,1)) %>%
  mutate(w2p = ifelse(is.na(Week_2)==T,0,1)) %>%
  mutate(w3p = ifelse(is.na(Week_3)==T,0,1)) %>%
  mutate(w4p = ifelse(is.na(Week_4)==T,0,1)) %>%
  mutate(w5p = ifelse(is.na(Week_5)==T,0,1)) %>%
  mutate(w6p = ifelse(is.na(Week_6)==T,0,1)) %>%
  mutate(Weeks_Picked = w1p+w2p+w3p+w4p+w5p+w6p) %>%
  mutate(games_picked = ((w1p*wk1_n)+(w2p*wk2_n)+(w3p*wk3_n)+(w4p*wk4_n)+(w5p*wk5_n)+(w6p*n))) %>%
  mutate(Season_Percent = round(((ifelse(is.na(Week_1)==T, 0, Week_1) + 
                             ifelse(is.na(Week_2)==T,0,Week_2) +
                             ifelse(is.na(Week_3)==T, 0, Week_3)+
                             ifelse(is.na(Week_4)==T,0,Week_4)+
                             ifelse(is.na(Week_5)==T,0,Week_5)+
                             ifelse(is.na(Week_6)==T,0,Week_5))/games_picked),4)) %>%
  select(name,hour, Week_1, Week_2, Week_3, Week_4, Week_5, Week_6, Percent, Weeks_Picked, Season_Percent) %>%
  arrange(desc(Percent), desc(Season_Percent)) %>%
  mutate(Adj_Season_Percent = round(Season_Percent*(Weeks_Picked/max(Weeks_Picked)),4))

#formating chart for stars 
improvement_formatter <- 
  formatter("span", 
            style = x ~ style(
              font.weight = "bold", 
              color = ifelse(x > .5, "green", ifelse(x < .5, "red", "black"))),
             x ~ icontext(ifelse(x == max(x), "star", ""), x))

improvement_formatter3 <- 
  formatter("span", 
            style = x ~ style(
              font.weight = "bold", 
              color = ifelse(x > .5, "green", ifelse(x < .5, "red", "black"))),
             x ~ icontext(ifelse(x == x[1], "star", ""), x))

# Creating individual results table
Week_6_indiv = formattable(indiv_disp,
            align =c("l","c","c", "c", "c", "c", "c","c","c", "c", "c", "c"), 
            list(
              `Indicator Name` = formatter("span", 
                                style = ~ style(color = "grey",font.weight = "bold")),
              "Percent" = improvement_formatter3, 
              "Season_Percent" = improvement_formatter,
              "Adj_Season_Percent" = improvement_formatter
              
))
```

```{r individual Display, echo=FALSE}
# Printing the individual table 
Week_6_indiv

class = indiv_disp %>% 
    group_by(hour) %>%
    summarise(Class_Avg = mean(Percent, na.rm = T))

class = class[-4,]
paste("Class correct percentage for the week is G1:", round(class[1,2],4),"G2:", round(class[2,2],4),"I1:", round(class[3,2],4), sep = " ")
paste("Best Prediction this week is hour", class$hour[which(class$Class_Avg==max(class$Class_Avg))])

indi = indiv_disp %>% 
  select(name, Week_1, Week_2, Week_3, Week_4, Week_5, Percent) %>%
  mutate(Week_1 = Week_1/(wk1_n))%>%
  mutate(Week_2 = Week_2/(wk2_n))%>%
  mutate(Week_3 = Week_3/(wk3_n))%>%
  mutate(Week_4 = Week_4/(wk4_n))%>%
  mutate(Week_5 = Week_5/(wk5_n))%>%
  as.data.frame()
na = rep(indi$name, 6)
we1 = c(indi$Week_1,indi$Week_2,indi$Week_3,indi$Week_4, indi$Week_5, indi$Percent)
we2 = c(rep("Week 1", length(indi$name)), rep("Week 2", length(indi$name)),
        rep("Week 3", length(indi$name)), rep("Week 4", length(indi$name)),
        rep("Week 5", length(indi$name)), rep("Week 6", length(indi$name)))
i_df = cbind.data.frame(na, we1, we2)

ggplot(i_df, aes(x = we2, y = we1, group = na, color = na))+
  geom_point()+
  geom_line()+
  geom_text_repel(aes(label=na),hjust=0, vjust=0)+
  ylim(c(0, 1)) +
  xlab("NFL Week") + 
  ylab("Correct Percentage")+
  ggtitle("Weekly Individual Correct Percentage")+
  theme_classic()

```

```{r pregame, eval=FALSE, include=FALSE}
#Predictions for the week
Pregame = tibble(Game = 1:length(games)) %>% 
  add_column(Prediction = pred)

pre_game = formattable(Pregame,
            align =c("c","c"), 
            list(
              `Indicator Name` = formatter("span", 
                                style = ~ style(color = "grey",font.weight = "bold"))))
pre_game
```
